name: PR Cargo Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "platform/**"

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    env:
      PYO3_PYTHON: /usr/bin/python3
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install yasm
        run: sudo apt-get update && sudo apt-get install -y yasm

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo check
        run: cargo build --features=fail-on-warnings
