import { useState } from "react";
import {
  Box,
  Button,
  Divider,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Stack,
  Text,
  useToast,
  Alert,
  AlertIcon,
  SlideFade,
} from "@chakra-ui/react";

type LoginStatus = {
  emailSent: boolean;
  isExistingUser: boolean | null;
  emailAddress: string;
};

export default function LoginLinkGenerator() {
  const [email, setEmail] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [loginStatus, setLoginStatus] = useState<LoginStatus | null>(null);
  const toast = useToast();

  const handleSendLoginEmail = async () => {
    if (!email || !email.includes("@")) {
      toast({
        status: "error",
        title: "Invalid email",
        description: "Please enter a valid email address",
        duration: 3000,
      });
      return;
    }

    setIsProcessing(true);
    setLoginStatus(null);

    try {
      const res = await fetch("/api/admin/login-link", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email }),
      });

      let data;
      try {
        data = await res.json();
      } catch (e) {
        throw new Error(`Server error (${res.status}): ${e instanceof Error ? e.message : "Invalid JSON"}`);
      }

      if (!res.ok) {
        throw new Error(data.error || "Failed to send login link");
      }

      setLoginStatus({
        emailSent: data.emailSent,
        isExistingUser: data.isExistingUser,
        emailAddress: email,
      });

      toast({
        status: "success",
        title: "Login email sent",
        description: `Login email has been sent to ${email}!`,
        duration: 4000,
      });

      setEmail("");
    } catch (error) {
      console.error("Error:", error);
      setLoginStatus({
        emailSent: false,
        isExistingUser: null,
        emailAddress: email,
      });

      toast({
        status: "error",
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to send login link",
        duration: 4000,
      });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <Box>
      <Heading as="h2" size="md" mb={4}>
        Login Link Generator
      </Heading>
      <Divider mb={5} />

      <Stack spacing={4}>
        <Alert status="warning" borderRadius="md">
          <AlertIcon />
          <Stack spacing={2}>
            <Text fontSize="sm">
              Login links generated by this tool will always sign users into{" "}
              <strong>GovClerkMinutes.com</strong>, regardless of where the tool is being used or
              which environment is active.
            </Text>
            <Text fontSize="xs" mt={2}>
              Developers should use the standard sign-in flow during local development as
              there&apos;s no need to create magic links for users in non-production environments.
            </Text>
          </Stack>
        </Alert>
        <FormControl isRequired>
          <FormLabel>Email Address</FormLabel>
          <Input
            type="email"
            id="email-input"
            placeholder="user@example.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            disabled={isProcessing}
          />
        </FormControl>

        <Button
          colorScheme="blue"
          onClick={handleSendLoginEmail}
          isLoading={isProcessing}
          loadingText="Sending..."
          width="full"
        >
          Send Login Email
        </Button>

        {loginStatus && (
          <SlideFade in={loginStatus !== null}>
            <Alert status={loginStatus.emailSent ? "success" : "error"} mt={4} borderRadius="md">
              <AlertIcon />
              <Text>
                {loginStatus.emailSent
                  ? `Login email sent to ${loginStatus.emailAddress}`
                  : `Failed to send login email to ${loginStatus.emailAddress}`}
                {loginStatus.isExistingUser !== null && (
                  <span> {loginStatus.isExistingUser ? "(existing user)" : "(new user)"}</span>
                )}
              </Text>
            </Alert>
          </SlideFade>
        )}
      </Stack>
    </Box>
  );
}
