export const GOOGLE_ADS_ID = "AW-17712526206";
export const GOOGLE_ADS_PURCHASE_CONVERSION_ID = "hmmpCJaj-bsbEP7m_v1B";
export const GOOGLE_ADS_SUBMIT_LEAD_FORM_CONVERSION_ID = "UdtbCPa768YbEP7m_v1B";
