#!/bin/bash

pushd refresh-server/

trap popd EXIT

set -e
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc cargo build --release --target="x86_64-unknown-linux-gnu"
xz --keep --force -9 target/x86_64-unknown-linux-gnu/release/refresh-server
rsync -v target/x86_64-unknown-linux-gnu/release/refresh-server.xz ec2:~/refresh.xz
ssh ec2 xz --force -d refresh.xz
