export const gc_segments = [
  {
    transcript_id: 33056,
    start: "0:00:00.030969",
    stop: "0:00:25.242219",
    speaker: "A",
    transcript:
      "We are open and we are live. Okay, sounds great. So thank you everyone for being here. I will call this meeting to order. And I will note that Corey is here from the Chamber of Commerce, the Davis Chamber of Commerce. And Mayor Arnold is here representing the city as am I. so",
    segment_index: 0,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:00:57",
    stop: "00:00:58",
    speaker: "UNASSIGNED_1",
    transcript: "this meeting.",
    segment_index: 0,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:01:01",
    stop: "00:01:02",
    speaker: "UNASSIGNED_2",
    transcript: "comment either.",
    segment_index: 0,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:01:17",
    stop: "00:01:19",
    speaker: "UNASSIGNED_3",
    transcript: "good. Okay.",
    segment_index: 0,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:05:47",
    stop: "00:05:47",
    speaker: "UNASSIGNED_4",
    transcript: "now",
    segment_index: 0,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:08:22",
    stop: "00:08:25",
    speaker: "UNASSIGNED_5",
    transcript: "And so",
    segment_index: 0,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:00.030969",
    stop: "0:00:25.242219",
    speaker: "A",
    transcript:
      "We are open and we are live. Okay, sounds great. So thank you everyone for being here. I will call this meeting to order. And I will note that Corey is here from the Chamber of Commerce, the Davis Chamber of Commerce. And Mayor Arnold is here representing the city as am I. so",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:00:57",
    stop: "00:00:58",
    speaker: "UNASSIGNED_1",
    transcript: "this meeting.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:01:01",
    stop: "00:01:02",
    speaker: "UNASSIGNED_2",
    transcript: "comment either.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:01:17",
    stop: "00:01:19",
    speaker: "UNASSIGNED_3",
    transcript: "good. Okay.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:05:47",
    stop: "00:05:47",
    speaker: "UNASSIGNED_4",
    transcript: "now",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:08:22",
    stop: "00:08:25",
    speaker: "UNASSIGNED_5",
    transcript: "And so",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:10:38",
    stop: "00:10:39",
    speaker: "UNASSIGNED_6",
    transcript: "And we used to",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:10:50",
    stop: "00:10:51",
    speaker: "UNASSIGNED_7",
    transcript: "So we'll",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:13:56",
    stop: "00:13:57",
    speaker: "UNASSIGNED_8",
    transcript: "But",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:25:33",
    stop: "00:25:33",
    speaker: "UNASSIGNED_9",
    transcript: "And,",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:26:26",
    stop: "00:26:29",
    speaker: "UNASSIGNED_10",
    transcript: "that you",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:28:29",
    stop: "00:28:39",
    speaker: "UNASSIGNED_11",
    transcript:
      "Can I go to the next slide, please? Oh, looks like, okay, I'll turn my video back on. So is there any",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:28:41",
    stop: "00:28:46",
    speaker: "UNASSIGNED_12",
    transcript: "to the end of your list. Yeah, okay, well, Very impressive list.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:28:56",
    stop: "00:28:56",
    speaker: "UNASSIGNED_13",
    transcript: "Okay.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:29:12",
    stop: "00:29:13",
    speaker: "UNASSIGNED_14",
    transcript: "Program",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:30:49",
    stop: "00:30:54",
    speaker: "UNASSIGNED_15",
    transcript: "session as well. great um",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:34:32",
    stop: "00:34:34",
    speaker: "UNASSIGNED_16",
    transcript: "you know yeah once",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:37:30",
    stop: "00:37:31",
    speaker: "UNASSIGNED_17",
    transcript: "It's,",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:37:39",
    stop: "00:37:40",
    speaker: "UNASSIGNED_18",
    transcript: "know, I",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:38:13",
    stop: "00:38:13",
    speaker: "UNASSIGNED_19",
    transcript: "I mean,",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:39:43",
    stop: "00:39:43",
    speaker: "UNASSIGNED_20",
    transcript: "But",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:46:14",
    stop: "00:46:14",
    speaker: "UNASSIGNED_21",
    transcript: "Okay.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:46:29",
    stop: "00:46:31",
    speaker: "UNASSIGNED_22",
    transcript: "I'm not seeing any raised hands.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:46:59",
    stop: "00:47:03",
    speaker: "UNASSIGNED_23",
    transcript: "And if I could just jump in here before you share.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:47:41",
    stop: "00:47:42",
    speaker: "UNASSIGNED_24",
    transcript: "For this meeting?",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:48:41",
    stop: "00:48:43",
    speaker: "UNASSIGNED_25",
    transcript: "Yep. That's correct.",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "00:49:00",
    stop: "00:49:07",
    speaker: "UNASSIGNED_26",
    transcript: "cuttings thanks cory bye everyone bye",
    segment_index: 0,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:28.617219",
    stop: "0:00:40.395969",
    speaker: "A",
    transcript:
      "so can we get an approval of the agenda we're usually very informal at this meeting so if everybody is okay with the agenda today can we just good okay sounds good are",
    segment_index: 1,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:28.617219",
    stop: "0:00:40.395969",
    speaker: "A",
    transcript:
      "so can we get an approval of the agenda we're usually very informal at this meeting so if everybody is okay with the agenda today can we just good okay sounds good are",
    segment_index: 1,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:42.792219",
    stop: "0:00:44.564094",
    speaker: "A",
    transcript: "are there any public comments I",
    segment_index: 2,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:50.504094",
    stop: "0:00:55.853469",
    speaker: "A",
    transcript:
      "okay and I don't recall getting anything in email at least the last time I checked for",
    segment_index: 2,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:47.972844",
    stop: "0:00:55.853469",
    speaker: "A",
    transcript:
      "I do not see any hands raised okay and I don't recall getting anything in email at least the last time I checked for",
    segment_index: 3,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:59.599719",
    stop: "0:01:00.865344",
    speaker: "A",
    transcript: "I have not received any written public",
    segment_index: 3,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:00:59.599719",
    stop: "0:01:00.865344",
    speaker: "A",
    transcript: "I have not received any written public",
    segment_index: 4,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:03.075969",
    stop: "0:01:16.356594",
    speaker: "A",
    transcript:
      "Okay. So then we will close public comment and move on to the approval of the minutes. The minutes were sent out in this email as well. And if everyone is good with the minutes. I'm",
    segment_index: 4,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:03.075969",
    stop: "0:01:16.373469",
    speaker: "A",
    transcript:
      "Okay. So then we will close public comment and move on to the approval of the minutes. The minutes were sent out in this email as well. And if everyone is good with the minutes. I'm",
    segment_index: 5,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:22.144719",
    stop: "0:01:28.523469",
    speaker: "A",
    transcript:
      "So then, this brings us to our updates and discussion items and there are a lot of them on this agenda.",
    segment_index: 5,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:22.144719",
    stop: "0:01:41.196594",
    speaker: "A",
    transcript:
      "So then, this brings us to our updates and discussion items and there are a lot of them on this agenda. I'm just going to let the dog in on my office. So we will move through all of the discussion items for number five. and then",
    segment_index: 6,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:30.075969",
    stop: "0:01:31.814094",
    speaker: "B",
    transcript: "I'm just going to let the dog in on my office.",
    segment_index: 6,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:44.892219",
    stop: "0:02:07.504719",
    speaker: "A",
    transcript:
      "it doesn't sound like currently we have anybody here from Davis downtown or visit YOLO. So we'll see what we do when we get to the bottom five, but we'll take public comment after five and six. All right. So the floor is yours, Corey. Okay,",
    segment_index: 7,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:33.653469",
    stop: "0:01:41.196594",
    speaker: "A",
    transcript: "So we will move through all of the discussion items for number five. and then",
    segment_index: 7,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:02:08.955969",
    stop: "0:04:58.904094",
    speaker: "B",
    transcript:
      "thanks Gloria. So yeah the first item here, oh Happy New Year to everyone. I mean I guess it's not too late in the year to keep saying that I guess January 31st is the deadline. So our installation dinner is Saturday February 18th. It's at the Arc Ballroom on the UC Davis campus. Right now, I believe we have 200 people attending. Last year, we had 205. It looks like we're going to have quite a few more than that, which is nice. We are celebrating all the award winners. So we have Business of the Year, Nonprofit of the Year, all the community award winners. We're also recognizing our new chair, Corey Day, who has already sort of taken the reins, but we're going to officially acknowledge him that night. It's going to be a great event. We're looking forward to it. We've sold all of our sponsorships. Like I said, attendance will be better than last year, which is nice to see. we're monitoring any sort of health and safety protocols. I know this time last year, you know, this time last year, you know, there was a concern. Are we even going to be able to do it? Do we have to cancel it? You know, we ended up doing the testing and the masks and things like that. So there are no specific regulations right now. There is a recommendation that we do wear masks indoors. It is university property. We are going to let our attendees know that, you know, if you want to bring a mask, wear it indoors. But there's no specific regulations that we have to follow to test anyone or make sure anybody's wearing their mask or anything like that this year. Of course, things could change. It's not for a few weeks. So, but we're monitoring that. We're really happy about the event though. I was very nervous just based on our budget, Nat, that we weren't going to make our budget, but this event is typically a good one. And it's a 1920 style event. So I know a lot of people are getting dressed up. I will be dressed up. And so it should be interesting. But that event, I'm looking forward to it. You know, we're going to have the We're going to have quite a few elected officials there, including in Davis. We've got a couple of assembly members coming, state senator coming, so should be nice, should be really good. So, Gloria",
    segment_index: 8,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:01:44.892219",
    stop: "0:02:07.437219",
    speaker: "A",
    transcript:
      "it doesn't sound like currently we have anybody here from Davis downtown or visit YOLO. So we'll see what we do when we get to the bottom five, but we'll take public comment after five and six. All right. So the floor is yours, Corey. Okay,",
    segment_index: 8,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:05:00.945969",
    stop: "0:05:46.660344",
    speaker: "B",
    transcript:
      "Gloria and Will, I'm just going to move through these. If you have questions, stop me or interrupt me or whatever. But our golf tournament, it is scheduled. We are doing it in the spring this year. We have been doing it in the fall for the last couple of years. We had a lot of pushback from people saying, you know, hey, can you schedule a different time? So we have been doing it in August, the last couple of years with the heat, the smoke and the school starting, not to say school starting is in the same category as heat and smoke, but, you know, there were a lot of challenges we had trying to get our golf tournament to where I thought it should be. So we changed the time. It's",
    segment_index: 9,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:02:08.955969",
    stop: "0:04:58.904094",
    speaker: "C",
    transcript:
      "thanks Gloria. So yeah the first item here, oh Happy New Year to everyone. I mean I guess it's not too late in the year to keep saying that I guess January 31st is the deadline. So our installation dinner is Saturday February 18th. It's at the Arc Ballroom on the UC Davis campus. Right now, I believe we have 200 people attending. Last year, we had 205. It looks like we're going to have quite a few more than that, which is nice. We are celebrating all the award winners. So we have Business of the Year, Nonprofit of the Year, all the community award winners. We're also recognizing our new chair, Corey Day, who has already sort of taken the reins, but we're going to officially acknowledge him that night. It's going to be a great event. We're looking forward to it. We've sold all of our sponsorships. Like I said, attendance will be better than last year, which is nice to see. we're monitoring any sort of health and safety protocols. I know this time last year, you know, this time last year, you know, there was a concern. Are we even going to be able to do it? Do we have to cancel it? You know, we ended up doing the testing and the masks and things like that. So there are no specific regulations right now. There is a recommendation that we do wear masks indoors. It is university property. We are going to let our attendees know that, you know, if you want to bring a mask, wear it indoors. But there's no specific regulations that we have to follow to test anyone or make sure anybody's wearing their mask or anything like that this year. Of course, things could change. It's not for a few weeks. So, but we're monitoring that. We're really happy about the event though. I was very nervous just based on our budget, Nat, that we weren't going to make our budget, but this event is typically a good one. And it's a 1920 style event. So I know a lot of people are getting dressed up. I will be dressed up. And so it should be interesting. But that event, I'm looking forward to it. You know, we're going to have the We're going to have quite a few elected officials there, including in Davis. We've got a couple of assembly members coming, state senator coming, so should be nice, should be really good. So, Gloria",
    segment_index: 9,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:05:49.208469",
    stop: "0:07:28.585344",
    speaker: "B",
    transcript:
      "in the springtime. Hopefully the weather will be good. It's the last Monday of April. We still have not decided where we're going to do it for the last four years. We've done it at El Macero, but we may end up doing it at Wild Horse. That is something that I just think because we have a couple of golf courses in the city it might be nice for the chamber to sort of uh spread the love or you know uh wild horse was a member for a number of years they haven't been a member for a couple of years i think this would bring them back and again i just think it makes sense to kind of spread the the event around a little bit uh last year's golf tournament we had 120 people 22 people uh we're hoping to have something similar this year so um we've already sold the the title sponsor and by popular demand our members want us to sell more alcohol sponsors i've been told that there are some organizations that sell alcohol at every hole i am not willing to do that um i may be fired because of that but uh we are selling i think three or four alcohol sponsors so uh one of our um very large companies in town uh he is going to come with some sort of crazy outfit on and serve alcohol all day long uh that um so our golf tournament is set we just don't know the location.",
    segment_index: 10,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:05:00.945969",
    stop: "0:05:46.660344",
    speaker: "C",
    transcript:
      "Gloria and Will, I'm just going to move through these. If you have questions, stop me or interrupt me or whatever. But our golf tournament, it is scheduled. We are doing it in the spring this year. We have been doing it in the fall for the last couple of years. We had a lot of pushback from people saying, you know, hey, can you schedule a different time? So we have been doing it in August, the last couple of years with the heat, the smoke and the school starting, not to say school starting is in the same category as heat and smoke, but, you know, there were a lot of challenges we had trying to get our golf tournament to where I thought it should be. So we changed the time. It's",
    segment_index: 10,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:07:32.854719",
    stop: "0:08:21.977844",
    speaker: "B",
    transcript:
      "I'm not sure what the annual chamber sponsor event is. This could be this. I may have. Kelly, this has got to be my fault. I must have been typing it like two in the morning. This may be our you know what I don't know what this is. Oh, I know what this is. Oh, so we held our first. This is the event for our annual sponsors. I'm sorry. We held the first one. This is the first one that we did. It was in December. The chamber has what we call our annual sponsors. These are companies that provide sponsorship money to the chamber in advance of all of the events happening. And we call them our annual sponsors.",
    segment_index: 11,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:05:49.208469",
    stop: "0:07:28.585344",
    speaker: "C",
    transcript:
      "in the springtime. Hopefully the weather will be good. It's the last Monday of April. We still have not decided where we're going to do it for the last four years. We've done it at El Macero, but we may end up doing it at Wild Horse. That is something that I just think because we have a couple of golf courses in the city it might be nice for the chamber to sort of uh spread the love or you know uh wild horse was a member for a number of years they haven't been a member for a couple of years i think this would bring them back and again i just think it makes sense to kind of spread the the event around a little bit uh last year's golf tournament we had 120 people 22 people uh we're hoping to have something similar this year so um we've already sold the the title sponsor and by popular demand our members want us to sell more alcohol sponsors i've been told that there are some organizations that sell alcohol at every hole i am not willing to do that um i may be fired because of that but uh we are selling i think three or four alcohol sponsors so uh one of our um very large companies in town uh he is going to come with some sort of crazy outfit on and serve alcohol all day long uh that um so our golf tournament is set we just don't know the location.",
    segment_index: 11,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:08:25.724094",
    stop: "0:08:55.339719",
    speaker: "B",
    transcript:
      "for the first time, we wanted to get them all together and sort of recognize them for all the financial assistance that they provide to us and all the things that we do in the community. So we held that in December. We were hoping for, I think we invited 110 people. We had 62 show up, which I thought was a good turnout. It was fun. We kind of gave crazy awards out. But these are companies that, for the most part, give the chamber most of our operating throughout",
    segment_index: 12,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:07:32.854719",
    stop: "0:08:21.977844",
    speaker: "C",
    transcript:
      "I'm not sure what the annual chamber sponsor event is. This could be this. I may have. Kelly, this has got to be my fault. I must have been typing it like two in the morning. This may be our you know what I don't know what this is. Oh, I know what this is. Oh, so we held our first. This is the event for our annual sponsors. I'm sorry. We held the first one. This is the first one that we did. It was in December. The chamber has what we call our annual sponsors. These are companies that provide sponsorship money to the chamber in advance of all of the events happening. And we call them our annual sponsors.",
    segment_index: 12,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:08:59.558469",
    stop: "0:09:59.970969",
    speaker: "B",
    transcript:
      "throughout the year. And so we wanted to recognize them, give them some time to tell us how their business is doing, because I wanted it to be an opportunity to hear from them. Because Chamber tries to do a lot of polling and that and serve information from surveys, but you can't get it from, you know, an event like this where people are face to face. So that's what that is. Ribbon cuttings. We are going to do a couple of ribbon cuttings, I believe, in February. One is the new Woodstocks. What, you know, what would Davis be without a second Woodstocks now? So we're going to be doing that. We talked to the owner of the company and she is trying to pick a date out. Looking forward to that. That one will be well attended. We won't have any problems. I mean, frankly, we might need a permit. It probably will be so big. The other ribbon cutting, I gotta be honest,",
    segment_index: 13,
    fast_mode: 1,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:08:25.724094",
    stop: "0:08:52.656594",
    speaker: "C",
    transcript:
      "for the first time, we wanted to get them all together and sort of recognize them for all the financial assistance that they provide to us and all the things that we do in the community. So we held that in December. We were hoping for, I think we invited 110 people. We had 62 show up, which I thought was a good turnout. It was fun. We kind of gave crazy awards out. But these are companies that, for the most part, give the chamber most",
    segment_index: 13,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:09:01.026594",
    stop: "0:10:37.568469",
    speaker: "C",
    transcript:
      "wanted to recognize them, give them some time to tell us how their business is doing, because I wanted it to be an opportunity to hear from them. Because Chamber tries to do a lot of polling and that and serve information from surveys, but you can't get it from, you know, an event like this where people are face to face. So that's what that is. Ribbon cuttings. We are going to do a couple of ribbon cuttings, I believe, in February. One is the new Woodstocks. What, you know, what would Davis be without a second Woodstocks now? So we're going to be doing that. We talked to the owner of the company and she is trying to pick a date out. Looking forward to that. That one will be well attended. We won't have any problems. I mean, frankly, we might need a permit. It probably will be so big. The other ribbon cutting, I gotta be honest, The name of the company evades me right now, but we are looking forward to doing that with them. I did not work on that one, but it looks like we will have two ribbon cuttings in February. And those are great. It's a great opportunity to welcome or expand a business in Davis. And one of the things I thought we would do, I'm always trying to improve things that the chamber does, or if we could do things better. Apparently what we used to do when we used to do ribbon cuttings, we used to invite somebody from the city, whether it was the mayor, city manager.",
    segment_index: 14,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:10:39.779094",
    stop: "0:10:48.992844",
    speaker: "C",
    transcript:
      "market the ribbon cutting along with that because obviously that will help promote it. So I think for these ribbon cuttings, we will probably do that.",
    segment_index: 15,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:10:51.844719",
    stop: "0:11:31.045344",
    speaker: "C",
    transcript:
      "get an invitation. And if you can't make it, you know, obviously maybe Josh can make it or Gloria or somebody else, just because I think when we do that, it means a lot to these businesses too, that somebody from the city shows up, especially from somebody from the city council. So I think we'll try to do that too. And we haven't done that for a few years, not because, you know, we didn't want to, it's just because, you know, we really didn't think about it, but I've heard from several of our members that we should really try to partner with the city a little bit more on ribbon cuttings. So we're looking forward to doing that. Can I get the next slide, please, Christina? Or thank you.",
    segment_index: 16,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:11:33.323469",
    stop: "0:12:44.822844",
    speaker: "C",
    transcript:
      "Our evening socials and mixers, most of you know the chamber does several of these a month. We're not doing any in January because we can never do them in January. People just, I guess, aren't recouped or decompressed from the holidays yet. But we are starting them in February. I think we're going to do two or three in February through the rest of the year. These are really an opportunity for a business to hold something in the evening, bring the community. They're free for the entire community. There's no membership requirement or anything. A lot of people think you got to be a chamber member to go. No, anybody is invited to these things. And people love them. I mean, probably because we bring wine to Raffle and people get that, but they're really a great opportunity to meet people, talk to people in the community. There's a lot of networking that goes on there. So we're looking forward to doing those. And actually, we're going to try something a little bit new this year. Instead of all of them in the evening, we're going to try a couple in the morning, which is my suggestion. I've got a lot of people,",
    segment_index: 17,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:12:47.657844",
    stop: "0:13:09.375969",
    speaker: "C",
    transcript:
      "people, geez, Corey, you know, I've got kids I've got to pick up. I've got soccer, football, whatever. So we're going to try to do a couple in the morning or maybe at the lunch hour and see how that goes. Hopefully that will, you know, at least anything, it'll mix things up a little bit and give people",
    segment_index: 18,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:13:11.400969",
    stop: "0:13:36.426594",
    speaker: "C",
    transcript:
      "people some variety. um the chamber has been very good i think at doing virtual information sessions i get a lot of people asking hey cory do a topic on this do a topic on that um so much so that i sort of run it by a committee of the chamber because i'm sort of tired of people complaining to me that i didn't like their idea so at least i can blame somebody else now um",
    segment_index: 19,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:13:39.042219",
    stop: "0:13:55.495344",
    speaker: "C",
    transcript:
      "we take a lot of the ideas and we run them through virtual sessions. We've got a couple of legal ones coming up. I think my video, I think I'm going to shut my video off. I think my internet connection is getting kind of funky. So sorry about that.",
    segment_index: 20,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:13:58.026594",
    stop: "0:16:57.829719",
    speaker: "C",
    transcript:
      "we are doing a cybersecurity bootcamp coming up with a local cybersecurity expert. It's free to attend. There's no requirement that you be a chamber member. Actually, I don't care who attends this one because there is so much going on right now with hacking and scams going on. This guy told me a couple of fairly large Davis businesses were hacked recently, lost thousands of dollars because of it. So this is a free session. The flyers on our website, I think we shared it with the city, but anybody can attend. We've got a landlord property manager boot camp. It's a forum that we've got an attorney coming. You know, the chamber has a number of landlords and property managers as members. We have a lot that are not. And we felt like this was I mean, I'll be honest with you. The last time we did this in partnership with the city and the city's rental resources program, there were a number of questions on there that I think are a little embarrassing by landlords. Pretty basic stuff that anybody in the industry should know. and so I you know I've I've had a chat with a number of city staff and now we need to do more of these and the chamber is more than willing to find attorneys to help help these folks out um and so we're doing our our next one I think it's in late late February we just got the flyer done again free for everybody to attend you don't have to be a chamber member um we're going to do another de-escalation training with the police department. Those are well attended with everything that's going on in the world. And, you know, we can't seem to de-escalate situations as well as I think we all want to. We are going to hold a couple of these each year. We are going to do this one virtually. We have been doing a number of them in person. There's a lot of people that like to do them in person, but we are going to do this one virtually because we've been asked to. because people can't always make the in-person ones. With the virtual ones, we can record a good quality session and people can view that recording at a later date. Other virtual sessions we've got, we've got one coming up with Senator Mike Thompson. I believe we've got one, oh, our state of the city, that'll be virtual. We've got another virtual one with a lawyer, an employment lawyer on all the new law employment laws and that for the new year so we got a lot of virtual information sessions they're all recorded they're all online people business people can view them whenever they want at their leisure um so yeah uh can we get the next slide please",
    segment_index: 21,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:17:00.360969",
    stop: "0:18:09.413469",
    speaker: "C",
    transcript:
      "um so as i mentioned our annual state of the city uh is coming up i believe it's wednesday march first. The flyer is out on that. This again is free to attend. We're happy to partner with the city on this. Obviously, we're going to hear from Will and from Mike Webb. We'll hear from Corey Day and then I'll do a very brief State of the Chamber as well. But we're it's always a very well attended session. We always help, you know, 100 to 150 people attend when we record it and post it on our Facebook. You know, I think the last time we had about 1200 people watch the recorded session, which is pretty good. I mean, that's a that's a pretty good viewing for people watching that kind of a virtual session that's recorded. So we're looking forward to it. It's always interesting to hear what, you know, is happening with the city. I'm sure we'll have a lively discussion. You know, there's always some interesting questions that come through. So, but we'll filter those and make sure, you know, we don't get anything too crazy.",
    segment_index: 22,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:18:13.379094",
    stop: "0:20:40.579719",
    speaker: "C",
    transcript:
      "Chamber board recruitment. We have, we have, Gloria, did you have a question? I'm sorry. No, go ahead. Okay. So our board, we just introduced several new board members. So I have been with the chamber five years now. And I will tell you there are only of our 20 board members. We only have, I think, two left from when I started. So we have a entirely new board. It's very new. Some of them are not new to the city or anything, but they are new to the chamber. It's interesting and exciting in a way, but there's a lot of things that they need to, you know, get to know about the chamber. And the chamber did add several seats to our board. So instead of 20 seats, we now have 23. And so if anybody, and obviously, we have a representative in our bylaws from the city, that's a, you know, permanent seat on the board and Gloria is, I believe, filling that role this year. And we also have a permanent non-voting role for the university. And Mabel Salon, she is going, I think Mabel is actually celebrating her 20th year on the board this year. So might have to do something special for her. But we also have 23 voting seats. We have 20 of them filled. So we have three seats. If anybody knows anyone, please send their names on. We would like to, I'll tell you one area that the chamber does not have any representation on is restaurants. we you know uh uh ted parks with woodstocks turned out this year or last year excuse me uh so we could really use a restaurant we've had several people inquire but they just don't know if they can fulfill the the time commitment and you know the last thing we want is somebody to to join but not be able to attend the meetings or participate in that but if anybody's interested, if you know anyone, you can let me know and I can forward their information on to our recruitment committee. But that is something that we'd like to do is have some new board members sign on.",
    segment_index: 23,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:20:42.689094",
    stop: "0:25:32.432844",
    speaker: "C",
    transcript:
      "on. We've got some new programs and services that we're going to be offering for 2023. We've got a brand new, I would call it a major event, the way we budgeted this thing. We've got the school district that is going to be a title sponsor of it. It's in the fall. It's going to be for families. I don't believe we're going to have any alcohol there. We are going to have a lot of family related stuff. We have been asked, when we did our last survey, one of the things that we got back was, hey, the chamber does awesome events. um we love them but can you do one for families where there's not alcohol and where there's not you know a lot of crazy stuff so we are going to do one in the fall uh bobby is still looking at venues for it uh it's going to be family oriented uh i know the school district is all on board with this uh we've already got a number of sponsors including the school district that have uh gave us money to do this. So we're looking forward to it. I'm not sure what it's called yet. I have my own opinion about that, but I think I've been summarily outvoted by most people, but we'll see. So I'm looking forward to that. We are bringing back our small business trade show. Apparently the chamber used to do this about 10 years ago. We stopped before the pandemic, But I wanted to bring this back. I think we're going to do this in November. I think it's important for small businesses to have an opportunity to showcase their programs, their services, and that. So we're looking forward to doing this. We're partnering with a number of different organizations, including YOLO and that. So there should be some, we're gonna have booths there. It's gonna be an informational trade show as well for employers. So I believe there's going to be a job center there as well for employees who are looking for jobs. So it should be good. I mean, I'm looking forward to that. Can I get the next slide please? Um, so one of the things that we realized, um, working on the Healthy Davis Together program was how much the business community supported or appreciated getting grants. Um, you know, they thought the process worked out well. They thought it was a great partnership. And so I looked around for other chambers that provided grants to businesses and I couldn't find one in California but I did find some out of state and I asked them how they did it now so our chamber is going to do that we're going to try to give out two grants this year one to a small you got to be a small business or a small non-profit you know we're not giving these out to large companies These are going to be for, you know, local small companies. We've got a set of criteria. We've got a selection committee that's going to look at applications. We're going to have a very simple application, one page application. You know, it's going to ask, you know, are you in Davis? How long have you been in Davis? Are you a chamber member? Do you have, you know, a business license? You know, what are you going to use the money for? How many employees do you have? You know, that kind of thing. And we're going to pick out a couple of one small business, one small nonprofit, and we're going to give them grants this year and let them do with the money, whatever they want to. Hopefully, one of the criteria is going to be using the money for some, you know, worthwhile purpose, you know, to hire somebody to expand, whatever. So I'm looking forward to that. I think that's a great program for the chamber to get involved with. We got the money. You know, one of the questions I get asked is, where are you getting the money? And we've solicited the money from our large companies, from our annual sponsors. They've contributed money into a fund and we continue to receive money from different businesses and they love the idea. You know, so there's, you know, I think we've got 10 businesses that have contributed to the fund already. Significant money. So I'm happy with that. I think that's great that we can do that and give back to the community. And so the other thing we're doing is our meetings with the manager. We are looking for businesses that want to meet with the city, to meet with the city manager and the mayor and, you know, just have a discussion. Our first one was with Recology. Kelly was there.",
    segment_index: 24,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:25:34.575969",
    stop: "0:26:21.066594",
    speaker: "C",
    transcript:
      "you know, I thought we had a great discussion. And Recology loved it. You know, and Recology is a big company. You know, they frequently reach out, but they thought it was just nice to be able to sit down, have a candid conversation about what's going on with their company, what's going on in Davis, what their business model is. And And I think we all got a lot out of it. I did. So one of the other things that we're looking at doing, I I've I've I've been surprised at how difficult this one has been is is some peer counseling. I'd like to take some of our more successful businesses that are chamber members and help businesses that are struggling with, you know, whatever resource just to give them a resource from a large company that needs help. and",
    segment_index: 25,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:26:23.935344",
    stop: "0:26:26.230344",
    speaker: "C",
    transcript: "part of the problem that I've had is trying to find people",
    segment_index: 26,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:26:29.639094",
    stop: "0:28:27.713469",
    speaker: "C",
    transcript:
      "know will devote the amount of time I think that this thing will require I haven't given up yet but it's still a work in progress but I but I'm you know maybe I'm biting off a little more than I can stomach but I would like to get the peer counseling program going I think there are businesses that reach out to the chamber frequently. They are not members of ours, but they need help. They need help with loans or finding the right staff or, I mean, just basic stuff too. Where do I get supplies? Where do I do this? Where do I do that? And I thought, you know, hey, it'd be nice to have sort of a business one-on-one peer counseling type of program. So I'm working on it and we'll see. We are, we're continuing to do our make Davis sparkle we've got one scheduled next. Oh no, this coming Saturday. The flyer is out, we've got, you know, I will tell you of all the things the chamber does um when we do our make davis sparkles and we post those photos the the people comment and love those photos the most i mean people really like the chamber coordinating cleanup days around the city i mean those are very very popular we're planning to do four or five of them i mean if we could do them every other day we would but we don't have the kind of you know resources we do have a number of companies partnering with us uh the police department so the city does partner with us um recology partners with us they give us the cans the recycling cans um we have companies that donate supplies and that we have uh companies that donate volunteers as well um so there's a lot of people that it's not just the chamber but there's a lot of people and organizations that help pitch in that make this help. And so our first one Saturday, I think the weather should be nice. So we'll be out there.",
    segment_index: 27,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:28:40.555344",
    stop: "0:28:41.719719",
    speaker: "C",
    transcript: "questions, Gloria? You've come",
    segment_index: 28,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:28:49.482219",
    stop: "0:28:54.359094",
    speaker: "A",
    transcript:
      "So I have some questions. Will, do you want to go first with any questions you might have?",
    segment_index: 29,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:28:54.544719",
    stop: "0:28:55.810344",
    speaker: "B",
    transcript: "have? No, go ahead, please.",
    segment_index: 30,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:28:57.227844",
    stop: "0:29:12.077844",
    speaker: "A",
    transcript:
      "So the rental resources program, I'm really glad to hear that you are going to do a repeat of that. I think that's a really important piece. And, well, no, not the rental resources. is the Landlord Security Deposit",
    segment_index: 31,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:29:14.339094",
    stop: "0:29:19.013469",
    speaker: "A",
    transcript: "presentation. So will you be partnering with Rental Resources on that?",
    segment_index: 32,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:29:19.570344",
    stop: "0:30:38.984094",
    speaker: "C",
    transcript:
      "Yes. Yeah. I've been talking to Patty over there quite a bit. And let me make something clear. So we have scheduled two forums. One is on security deposits. The other one is on lease provisions. and we're going to do the lease provisions one first. We're going to do security deposits in April or March. And the reason why we decided to do that was because there's a lot of questions right now about signing leases and lease provisions. I mean, there's a lot of people that, there's a lot of landlords that, I mean, there's a lot of landlords that don't even use a written lease. You know, it's just a verbal, which I can't believe in this day and age. But so we decided to move that first. And so we're going to do lease provisions. We're going to do security deposits. I think we're going to do one on roommate situations, because obviously that's a big issue in Davis. We're going to do one on abandoned property. We're going to do one on, I mean, we've got a whole series of these lined up and we want to focus on particular issues that are important to being a landlord or property manager, but also that are unique to Davis to being a college town. So yeah, we",
    segment_index: 33,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:30:38.612844",
    stop: "0:30:41.009094",
    speaker: "A",
    transcript: "yeah, we are partnering",
    segment_index: 34,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:30:39.929094",
    stop: "0:30:47.404719",
    speaker: "C",
    transcript:
      "we are partnering with the city and the rental resources program. Yes. And they will have somebody on each virtual",
    segment_index: 35,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:30:54.897219",
    stop: "0:31:13.476594",
    speaker: "A",
    transcript:
      "so then the other question i had was about the peer counseling i think that you know again that is something that um you know i i really applaud you for uh you know trying to help businesses that that you know are struggling or you know having uh questions And",
    segment_index: 36,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:31:15.585969",
    stop: "0:31:52.778469",
    speaker: "A",
    transcript:
      "do you, I know that a while, it's been a while now, but there was sort of like the satellite to the Small Business Association that would run out of the chamber, I believe. And I know that they have like mentor, mentors, like retired business people, or even just people who have the time to mentor. and I'm just wondering if you partnered with Small Business Association, if maybe that would be a good way to recruit some folks.",
    segment_index: 37,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:31:53.402844",
    stop: "0:32:34.122219",
    speaker: "C",
    transcript:
      "So, Gloria, that's a great question. We are partnering with them. We actually, they were out of the chamber office. When we shut our office down, we do have a relationship with them. We are actually co-partners with them on a new program that is starting, you know, how to start a business. And there's a number of classes within that education module that they are presenting, but we're one of the partners with. We have talked to them about the peer-to-peer counseling and that, and there are resources there.",
    segment_index: 38,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:32:36.754719",
    stop: "0:33:28.965969",
    speaker: "C",
    transcript:
      "And that's a great point. I mean, that may be something that we need to do. What I was looking at doing was doing something with Davis businesses, Davis specific, because as I've learned, and I'm not an expert, but as I've learned, there are some unique nuances to being a business in Davis. And I think some businesses struggle with that. They struggle with a college town. They struggle with, you know, the ebbs and flows when the kids aren't here and the students aren't here. You know, they, and I think some of them struggle with how to use social media appropriately. And so I wanted to get Davis specific businesses to help out with some of that stuff. But you make a good point. And that may be where we go.",
    segment_index: 39,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:33:29.691594",
    stop: "0:34:00.066594",
    speaker: "A",
    transcript:
      "go. Well, and I'm wondering if maybe even some of our Davis businesses would want to sign up for, you know, to be to be part of the mentorship through the Small Business Association, maybe if they knew that that existed or people that have retired out of businesses in Davis that would, you know, would want to be part of this group. And then, you know, you could have folks that have had that experience as part of that pool.",
    segment_index: 40,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:34:00.572844",
    stop: "0:34:02.294094",
    speaker: "C",
    transcript: "pool. Yeah, that's a great idea.",
    segment_index: 41,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:34:03.576594",
    stop: "0:34:32.213469",
    speaker: "A",
    transcript:
      "And then the last two questions I have are around the Make Davis Sparkle. I'm really excited. I participated in that a couple of times and it was a lot of fun and um and i know that the downtown streets team is getting up and going um i think that they might be you know great uh partners is you know to to include in that i don't think they would be ready for this saturday but",
    segment_index: 42,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:34:34.491594",
    stop: "0:35:44.640969",
    speaker: "C",
    transcript:
      "so what we're doing is are the the so we know that's getting going We are holding these outside of downtown. So, because we know that, you know, that program is going to service downtown primarily, but our April one is going to be the day after picnic day. And that is one, so we did that last year. There were a lot of people said, oh, geez, I can't do it the day after picnic day for obvious reasons. And I'm like, well, we need to do it the day after because, you know, the day after that is a Monday and businesses are coming back. So I was there last Sunday or that Sunday last year and downtown needed it. So we're going to do it again the day after picnic day and maybe we can coordinate with that group but um you know yeah we got to clean up downtown the day after sure um so but that's a great idea glory partnering with them especially if we do one downtown but outside of that outside of picnic day we are scheduling all of these outside of downtown so we can do okay that's",
    segment_index: 43,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:35:44.640969",
    stop: "0:36:15.150969",
    speaker: "A",
    transcript:
      "that's that's even more exciting that's great um and then my last question was around some of the events that you have. I'm glad to hear you're partnering with the school district around some family, you know, families and like that. It's a great way to, you know, have families, you know, know about the businesses that are available in our community. Did I not see Celebrate Davis on your list? Oh,",
    segment_index: 44,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:36:16.939719",
    stop: "0:36:29.039094",
    speaker: "C",
    transcript:
      "well, that's my fault. It is on the list. I just included a couple at the beginning of the year. I just was wondering",
    segment_index: 45,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:36:27.992844",
    stop: "0:36:32.363469",
    speaker: "A",
    transcript: "I just was wondering if maybe you had decided to go away from it. No, no,",
    segment_index: 46,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:36:31.958469",
    stop: "0:36:33.561594",
    speaker: "C",
    transcript: "from it. No, no, no, no, no. I know there's been",
    segment_index: 47,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:36:32.869719",
    stop: "0:36:33.932844",
    speaker: "A",
    transcript: "no, no. I know there's been a...",
    segment_index: 48,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:36:34.253469",
    stop: "0:36:35.603469",
    speaker: "C",
    transcript: "Celebrate David's life. It's been challenging",
    segment_index: 49,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:36:34.388469",
    stop: "0:36:36.582219",
    speaker: "A",
    transcript: "Celebrate David's life. It's been challenging sometimes. We",
    segment_index: 50,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:36:36.801594",
    stop: "0:37:30.210969",
    speaker: "C",
    transcript:
      "We had the biggest attendance last year, I think, since 2015. So it was pretty well. We had some complaints about not enough food trucks. And, you know, last year was a bit challenging with our vendors just because staffing was an issue. We had a lot of businesses that always have participated with us, but because of staffing issues they had, they couldn't participate. So we're trying to work on that early, but no, we've got it scheduled. It's scheduled, I believe, for Friday, May 12th. I could be wrong, but it's the second Friday in May. We got it all ready to go. it's going to be a great event we got a lot of people already signed up for it.",
    segment_index: 51,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:37:32.843469",
    stop: "0:37:37.821594",
    speaker: "C",
    transcript: "you know, I'm looking forward to it again. It's, you know, I, you",
    segment_index: 52,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:37:40.690344",
    stop: "0:38:12.246594",
    speaker: "C",
    transcript:
      "mean, the one other area is the fireworks. I am not a fan of fireworks, but I have been outvoted by my board and others who like the fireworks show. And believe me, you know, at my request, we researched doing a lot of other things, drone shows, light shows. I mean, you go down the list. The cheapest drone and light show I could get a quote for was $50,000.",
    segment_index: 53,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:38:14.811594",
    stop: "0:39:07.259094",
    speaker: "C",
    transcript:
      "we can't afford that. So, you know, and I've reached out to members of the community who reach out to me and say, Corey, we're glad you don't like fireworks. You know, these are folks who don't like fireworks because it, you know, and I get it. They're loud, they're smoky, it's a fire hazard. I mean, I get that. I'm not a fireworks fan, but I am a fan of doing something that people like. And we did a survey this last year and we had a lot of responses and people liked the fireworks. But I get those complaints, and I'm sure you do, I know you do too, Gloria, about people in the community that don't like fireworks. And I have conversations with them and I tell them, I say, look, you know, until you can find me a reasonable alternative that doesn't cost $50,000. I mean, you know, we got to look at the fireworks show.",
    segment_index: 54,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:39:09.705969",
    stop: "0:39:42.173469",
    speaker: "A",
    transcript:
      "Sure. I understood. um so the other thing that i would be curious about and we don't have to discuss it now but i know that you know we're having some challenges with like inflatables and the insurance around that we had a non-profit that i'm connected with had a a lot of challenges in in trying to find a company that was going to meet the city's requirement for inflatables and so i'd be curious to know how you solve that.",
    segment_index: 55,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:39:45.008469",
    stop: "0:39:52.129719",
    speaker: "A",
    transcript:
      "before that, I want to make sure that Will has an opportunity to chime in here if he has any.",
    segment_index: 56,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:39:54.070344",
    stop: "0:40:01.073469",
    speaker: "B",
    transcript:
      "Yeah, thanks. And I'm sorry, I got booted off my computer. So I'm on my phone now. But the connection seems pretty stable. Thanks,",
    segment_index: 57,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:40:03.115344",
    stop: "0:43:47.502219",
    speaker: "B",
    transcript:
      "Thanks, Corey. I appreciate the presentation. It's a lot of, you know, it's a good time to be having this presentation at the beginning of the calendar year and we can kind of see how the calendar goes. I'm definitely on board for ribbon cuttings and whatnot to, you know, bring some whatever you think the mayor would bring to that. And so very happy to do that. And I've already spoken with Mike and on the chamber state of the city. And so we're working on that. I also am a big fan of like Make Davis Sparkle. I've I've participated in years past and my family has, you know, it gets very good. It's good PR all around. I think everybody's happy to see it. It also, you know, has the added benefit of actually making a difference. And that's, as you know, one of the biggest complaints we received recently when we were making that decision about what to do with that half block of G Street that's currently pedestrian only. That one of the major complaints folks had there was the lack of cleanliness. and you know we've really put ourselves out there as saying we're going to address that and so we will be calling upon our our partners in the business community particularly the chamber and the davis downtown to ensure that you know we sort of put our actions where our mouth is in terms of keeping that and all areas that are commercial areas in town as clean as they possibly can be. I know there's some acute things that crop up if somebody, you know, does something over the middle of the night and then the shop owner has to arrive to see the result of it the next morning. Very hard to have effective, you know, cleaning of that in the interim wee hours of the morning. But knowing that maybe there's somebody between the city and our business partners out there that's going to address it fast and those things aren't going to linger, we know they're going to be dealt with quickly i think will give folks a lot more comfort um i don't really look i've tried to render an opinion on the fireworks debate i don't particularly like the the loudness and the smokiness that goes along with it and we did a good friend of mine um in davis uh dog did um jump the fence and get hit by a car many, many, many, many years ago during 4th of July. And so I would love to see, I mean, something cool done in another way. And I've seen versions of it, but we got, we performed the same exercise that you did in terms of fact-finding when we were looking at alternatives to our 4th of July city firework show. And we came to much of the same conclusion, which is you either spend the same amount and have a much, much, much smaller, shorter show that would be really diminutive sort of by comparison to past years, or it's an exorbitant amount to have a show the sort of size, scope and length of the current fireworks show. So I get it. It's a struggle. I am also curious, having dealt with, you know, insurance for big events, I think particularly big events that have had, you know, the bounce houses and whatnot. I am curious for your answer to Gloria's question about your experience there too. I think that's all I have for now. Thanks.",
    segment_index: 58,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:43:49.712844",
    stop: "0:44:57.938469",
    speaker: "C",
    transcript:
      "Thanks. So, so yeah, thanks, Will. You know, I mean, I'll be reaching out to you for ribbon cuttings and that and whatever the chamber can assist with on, you know, helping clean up the city, you know, let us know. But Gloria, back to the inflatables, you know, we did have the issue last year with our Celebrate Davis, because we do have sack party junk come in and bring the inflatables and the kids. Are you referring to the liability insurance? Okay. Yeah. Well, I mean, the, I think the simple answer is the chamber already has the that liability coverage. And so for us to meet the city's requirement it it was easy I mean we we didn't have to do anything additional and I know that there's other um uh non-profits out there that may not have that level of insurance but we the chamber already does so we were already in compliance before the city put that into effect So does that answer your question?",
    segment_index: 59,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:44:57.938469",
    stop: "0:45:14.577219",
    speaker: "A",
    transcript:
      "question? Well, the issue that I had was that the nonprofit that I was working with also had the coverage, but the bounce house company needed to have that same level. And there were none that I could find all the way to the Bay Area that had that coverage.",
    segment_index: 60,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:45:15.032844",
    stop: "0:46:13.555344",
    speaker: "C",
    transcript:
      "Oh, I see. I see. Okay. Well, you know, I can talk to Bobby and find out, you know, what she did on that. But yeah, for us, I mean, we use we've used sack party jumps for you know i don't know how many years and it was good i the one the one nuance that we did this past year in 2022 was that we actually instead of using their employees we actually leased the inflatables the chamber was leasing the inflatable from them and we used our own staff to monitor it to do all of that. So that was one nuance that we, it actually saved us some money doing that. So, which was nice, but yeah, I apologize about doing that with Celebrate Davis. It's our biggest event and that I just left it off. I figured I could talk about it in April.",
    segment_index: 61,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:46:15.158469",
    stop: "0:46:28.270344",
    speaker: "A",
    transcript:
      "All right. No worries. So if there's not any more questions here between us, I'm going to see if there's anything for public comment on this.",
    segment_index: 62,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:46:32.168469",
    stop: "0:46:55.692219",
    speaker: "A",
    transcript:
      "Okay, great. So that brings us to item six, and we don't have any of our partner organizations that have come in. So I guess we'll keep moving on down the agenda here. All right. So these are our future meetings. it looks like we'll be meeting with Visit YOLO in February.",
    segment_index: 63,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:47:02.627844",
    stop: "0:47:05.479719",
    speaker: "A",
    transcript: "Yeah, sorry, I forgot to ask staff if they had anything.",
    segment_index: 64,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:47:05.699094",
    stop: "0:47:39.786594",
    speaker: "D",
    transcript:
      "I've had some initial conversation with Corey about this, but as of March, we will need to go back to in-person meetings. and so that may necessitate a change of day or time of the meeting. And Corey is working on, given the chamber's current situation, without an office specifically in town, working on figuring out how that will work for the chamber. So more to come on that, but just a reminder that as of the next chamber meeting, which would be April, we would presumably be in person.",
    segment_index: 65,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:47:44.798469",
    stop: "0:47:50.620344",
    speaker: "D",
    transcript: "Correct. So for the two by twos as of March, we'll be back to in-person meetings.",
    segment_index: 66,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:47:51.244719",
    stop: "0:47:55.075344",
    speaker: "A",
    transcript: "Okay. We have them in the city hall.",
    segment_index: 67,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:47:56.003469",
    stop: "0:48:06.955344",
    speaker: "D",
    transcript:
      "Yes, we have had them in the city hall before, and they're just working on who would be participating in person. Is that an accurate description of our conversation?",
    segment_index: 68,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:48:07.191594",
    stop: "0:48:26.918469",
    speaker: "C",
    transcript:
      "Yeah, I mean, the next chamber one is April. We can make the April and then the July one. I will not be around for October, so I will need to find a suitable replacement. But April and July are fine. I've got those covered. Yeah. Great.",
    segment_index: 69,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:48:29.787219",
    stop: "0:48:39.827844",
    speaker: "A",
    transcript:
      "Great. Okay. If there's not any last-minute thoughts, we are out of time, I think. Is that correct?",
    segment_index: 70,
    fast_mode: 0,
    is_user_visible: 1,
  },
  {
    transcript_id: 33056,
    start: "0:48:43.489719",
    stop: "0:48:59.976594",
    speaker: "A",
    transcript:
      "yes thank you so much cory uh sounds like you know you're got your hands full and doing a great job uh keeping all our businesses engaged and if you have anything uh that you need just please reach out and i look forward to those ribbon",
    segment_index: 71,
    fast_mode: 0,
    is_user_visible: 1,
  },
];
