export const BOTTOM_BAR_HEIGHT = 88;
export const AUDIO_PLAYER_HEIGHT = 80;
export const AUDIO_PLAYER_BOTTOM_OFFSET = 4;
export const CONTENT_BOTTOM_PADDING = 20;
export const LONG_PRESS_DELAY = 500;
export const RESIZE_DEBOUNCE_DELAY = 100;

export const LAYOUT = {
  BOTTOM_BAR_HEIGHT,
  AUDIO_PLAYER_HEIGHT,
  AUDIO_PLAYER_BOTTOM_OFFSET,
  CONTENT_BOTTOM_PADDING,
  LONG_PRESS_DELAY,
  RESIZE_DEBOUNCE_DELAY,
} as const;
